### ISSUE TITLE
ngcc not changing node_modules/@danielmoncada/angular-datetime-picker code

### ISSUE THREAD

**Issue by stepet80** [danielmoncada/date-time-picker#100]
Ngcc doesn't seem to be adapting the package? Is it a known issue or am I doing something wrong.
I have a script postinstall: 'ngcc'. Other packages are being tweaked by ngcc...

**Comment by stepet80** [comment]
Ok nevermind. i did 'ngcc --target @danielmoncada/angular-datetime-picker' and it told me moment was missing as a dependency. Maybe it should be added as a peer dependency?

**Comment by danielmoncada** [comment]
@stepet80  yeah, the dependency has been there since I forked the original. This is because the  author added the adapters as part of the package itself.

See discussion at: https://github.com/danielmoncada/date-time-picker/issues/20
