### ISSUE TITLE
var _moment__default = 'default' in _moment ? _moment['default'] : _moment;

### ISSUE THREAD

**Issue by stepet80** [danielmoncada/date-time-picker#101]
We have an issue with the umd bundle:
var _moment__default = 'default' in _moment ? _moment['default'] : _moment;

danielmoncada-angular-datetime-picker-10.js:7 Uncaught TypeError: Cannot use 'in' operator to search for 'default' in undefined

We are not using moment and don't have a _moment variable?

Could you make the library working without moment?

**Comment by danielmoncada** [comment]
@stepet80 did you fix the issue?

You do not have to use the moment adapter.. the the adapter itself is included in the package (this was from the initial project). 

For now, even if you are not using moment, you will need to add it as a devdependency.
