### ISSUE TITLE
Owl date picker- panel class doesn’t seem to work

### ISSUE THREAD

**Issue by shakedhaim** [danielmoncada/date-time-picker#102]
I’m trying to override the date picker css with panel class, and it doesn’t seem to work.

HTML:
<div [owlDateTimeTrigger]=“dt”>
<input [owlDateTime]=“dt”>
<owl-date-time [panelClass]=“date-picker” #dt> </owl-date-time>
</div>

CSS:
.date-picker {
  display: none;
}

I’m trying this and the date picker is still shown.

**Comment by danielmoncada** [comment]
@shakedhaim  have you tried setting ngdeep?

```css
.date-picker ::ngdeep {
display: none;
}
```

**Comment by danielmoncada** [comment]
abandoning, as there has not been an update.
