### ISSUE TITLE
min property in edit page doesn't accepts the previous dates

### ISSUE THREAD

**Issue by Chinna2405** [danielmoncada/date-time-picker#103]
Hi,
I have used ng-pick-datetime in a project which has a create and edit page. On the create I have added the min as today's date if some one is creating with today's date and saving on going to the edit page the update button is enabled until today when we try to open the created one on the next date then the update button is disabled.
It accepts the ngModel value but the date wasn't today hence it is not accepted by the picker.

Thanks in advance.

**Comment by danielmoncada** [comment]
@Chinna2405  can you post your code? Also note that the package you're using is different than package.

**Comment by danielmoncada** [comment]
closing old topic, no responses
