### ISSUE TITLE
Translate buttons Not working

### ISSUE THREAD

**Issue by zak293** [danielmoncada/date-time-picker#108]
Hey,
I try translate button cancel and set. My code below. What is wrong ?
I see always default labels.

Thanks :)

import {
  OWL_DATE_TIME_FORMATS,
  OWL_DATE_TIME_LOCALE,
  OwlDateTimeIntl,
  OwlDateTimeModule,
  OwlMomentDateTimeModule
} from '@danielmoncada/angular-datetime-picker';

class DefaultIntl extends OwlDateTimeIntl {
  public cancelBtnLabel = 'TEXT FOR CANCEL';
  public setBtnLabel = 'TEXT FOR SET';
}

providers: [
    {provide: OwlDateTimeIntl, useClass: DefaultIntl},
  ]

**Comment by satifant** [comment]
It works for me with 

```
@Injectable()
class DefaultIntl extends OwlDateTimeIntl {
...
}
```
You might be missing `@Injectable()`?

**Comment by fdc80** [comment]
@zak293  did you solved issue?

**Comment by danielmoncada** [comment]
@zak293 closing, as guidance has already been provided to solve your issue.
