### ISSUE TITLE
Adding and removing elements

### ISSUE THREAD

**Issue by abdulrahman1997x** [danielmoncada/date-time-picker#111]
Hey everyone
I would like to know if there's a way to add or remove the default buttons or adding new element to the time picker.

**Comment by danielmoncada** [comment]
@abdulrahman1997x  there's no way to move elements natively. 

What are you looking to add  / remove, and why? I guess you could also go more of ad hoc route and remove stuff from the DOM.

**Comment by danielmoncada** [comment]
closing, old topic, no reponses
