### ISSUE TITLE
Tabindex inside calender is not working correctly

### ISSUE THREAD

**Issue by bpanteleev** [danielmoncada/date-time-picker#117]
Tabindex inside calendar only allows to select a single date (i.e. only 7th day of the month).

![image](https://user-images.githubusercontent.com/82899736/116811436-e8b7ea80-ab51-11eb-8d77-73baf1998d5b.png)

Expected behavior: it should be possible to select any date via tab

**Comment by danielmoncada** [comment]
@bpanteleev the calendar days themselves do not tab. You can select days within the calendar using your keyboard arrows and pressing "enter" when you want a particular day selected.
