### ISSUE TITLE
zone.js:699 Unhandled Promise rejection: Missing locale data for the locale "ru"

### ISSUE THREAD

**Issue by dvkudashev** [danielmoncada/date-time-picker#12]

**Comment by danielmoncada** [comment]
@dvkudashev  any more info on this? Can you update the description of the issue and copy/paste the error?

**Comment by dvkudashev** [comment]
If you want to import locale data for other languages, you can do it manually:

**Comment by dvkudashev** [comment]
src/app/app.module.ts

import { registerLocaleData } from '@angular/common';
import localeRu from '@angular/common/locales/ru';

// the second parameter 'ru' is optional
registerLocaleData(localeRu, 'ru');
