### ISSUE TITLE
Allow customization for strings

### ISSUE THREAD

**Issue by jnthnwn** [danielmoncada/date-time-picker#128]
It would be useful to allow the user to customize the display text for the different UI elements and defaulting to the strings defined by `OWL_DATE_TIME_LOCALE`. For example, specifying MTWTFSS for the days of the week instead of short form (e.g. Mon) at the top of the calendar, or setting different text for the cancel/set buttons.

**Comment by dsnoeck** [comment]
See: https://danielykpan.github.io/date-time-picker/#locale-formats
And also: https://github.com/danielmoncada/date-time-picker/issues/54
