### ISSUE TITLE
Moment support

### ISSUE THREAD

**Issue by martinbianchi** [danielmoncada/date-time-picker#14]
Hi Daniel thank you for reactivate the project.
I've been using ng-pick-datetime with moment, so I had to install ng-pick-datetime. At the moment the library is throwing errors because they expect to import things from the old library.

There are a way to fix this and continue using moment?

**Comment by danielmoncada** [comment]
@martinbianchi you will need to uninstall the old components. This new version has the moment adapter as part of it.

The adapter it called:

> MomentDateTimeAdapter

**Comment by martinbianchi** [comment]
Great! thank you!
