### ISSUE TITLE
Testing with jest - Unexpected value 'OwlDateTimeModule' imported by the module

### ISSUE THREAD

**Issue by inpercima** [danielmoncada/date-time-picker#150]
I like this component and I also will help if needed.

At the moment I do have some trouble with the current version 13.1.1 and testing my angular app with jest.
I have no idea if this is connected to the issue: https://github.com/danielmoncada/date-time-picker/issues/141.

I have a shared Module importing and exporting `OwlDateTimeModule` and `OwlNativeDateTimeModule`.

I include it in my test and I got following error:
```
Unexpected value 'OwlDateTimeModule' imported by the module 'SharedModule'. Please add an @NgModule annotation.
```

**Comment by danielmoncada** [comment]
thanks @inpercima appreciate you willing to help. let me try and work on the ng13 upgrade, then you can retest to see if it fixes it. I'm assuming we just need to annotation added.
