### ISSUE TITLE
MY_MOMENT_FORMATS: parseInput is not working

### ISSUE THREAD

**Issue by khurramIlyas** [danielmoncada/date-time-picker#16]
I am setting following formats but `parseInput` is not working for me. I expect that value that I will receive in my form control will be as per format provided in `parseInt `but it always set value in a different format.

Actually, I want to have different date formats for display & actual value that will be passed to form control. 
```
export const MY_MOMENT_FORMATS = {
    parseInput: 'YYYY-MM-DD HH:mm:ss',
    fullPickerInput: 'MMM DD, YYYY hh:mm A',
    datePickerInput: 'MMM DD, YYYY',
    timePickerInput: 'hh:mm:ss A',
    monthYearLabel: 'MMM YYYY',
    dateA11yLabel: 'LL',
    monthYearA11yLabel: 'MMMM YYYY',
}
```

**Comment by danielmoncada** [comment]
Have you provided a custom 'CustomDateTimeAdapter'?

**Comment by danielmoncada** [comment]
@khurramIlyas hello is this still an issue? it's about almost 4 months and I haven't heard back.

**Comment by khurramIlyas** [comment]
Hi

Apologies for not following. I don't know how I missed the first response
of 2nd March from you. But I am not using this package anymore. I don't
actually even remember.
