### ISSUE TITLE
Angular V14 support

### ISSUE THREAD

**Issue by klemenzeleznik** [danielmoncada/date-time-picker#160]
Could Angular V14 support be added.

Thanks

**Comment by crh225** [comment]
https://github.com/danielmoncada/date-time-picker/pull/137/commits/a0d7d5151b4bfbc3d2a2493182fe0c328b19bbc4
Can probably use this pr as a reference

**Comment by danielmoncada** [comment]
> [a0d7d51](https://github.com/danielmoncada/date-time-picker/commit/a0d7d5151b4bfbc3d2a2493182fe0c328b19bbc4) Can probably use this pr as a reference

yep, I know how to migrate.

I'll work on this later this week.. currently at a conference

**Comment by BastienLedon** [comment]
Ah my bad, I didn't see your comment and just created a PR, you can close it if you prefer https://github.com/danielmoncada/date-time-picker/pull/161

**Comment by danielmoncada** [comment]
@BastienLedon no problem, appreciate the PR. I can merge it and publish when I get back

**Comment by NetWin** [comment]
Is there any update on the Angular14 support? 
> I'll work on this later this week.. currently at a conference

Are you back again? ^^
