### ISSUE TITLE
Max Date doesn't work properly 

### ISSUE THREAD

**Issue by imdanielaalves** [danielmoncada/date-time-picker#164]
**Angular Version:** 12.2.13
**Date Time Picker Version:** 13.1.1
**Date Time Picker Dayjs Adapter:** 1.1.1

I'm replacing the MomentJS to DayJS in my project.
When I define the 'max' input with the current date, in the datepicker I can't select the current day. If I enter manually works.

**Max Date:** 26.07.2022 13:49

**Date Time Picker:**
![image](https://user-images.githubusercontent.com/89107468/181010143-9e38fac2-f5aa-4ceb-b223-80ef82f6cc3d.png)

Do you have any idea or solution to fix this?

The date input should be always a dayjs or can I use ISO format?

**Comment by duxor** [comment]
@imdanielaalves Yes, the issue is related to the Day.js adapter `@danielmoncada/angular-datetime-picker-dayjs-adapter`.

Milliseconds make a difference. I will create a PR.

**Comment by danielmoncada** [comment]
@duxor PR looks good. Will merge 👍 
@imdanielaalves please update the dayjs adapter to the latest
