### ISSUE TITLE
danielmoncada / date-time-picker moment

### ISSUE THREAD

**Issue by nharshavreddy** [danielmoncada/date-time-picker#169]
The time picker not working properly "@danielmoncada/angular-datetime-picker-moment-adapter" with adapter we in the angular 13 we are not able to fix.
Can you please me how use moment

**Comment by danielmoncada** [comment]
@nharshavreddy hello, per the read me, the current version does not support ng 13. if you need ng 13 support, use the latest version 13 in npm (https://www.npmjs.com/package/@danielmoncada/angular-datetime-picker/v/13.1.1)
