### ISSUE TITLE
Angular 15 Support

### ISSUE THREAD

**Issue by mmoreno79** [danielmoncada/date-time-picker#172]
Currently the latest angular version supported is 14. Can we get angular 15 added?

**Comment by jtc10005** [comment]
Looks like PR #171 is to do this.

**Comment by KeithGillette** [comment]
In attempting to upgrade from Angular 14.2.7 to 15.0.2, I get the following build error:

```
./applications/browser/src/styles.scss - Error: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Package path ./assets/style/picker.min.css is not exported from package /path/to/node_modules/@danielmoncada/angular-datetime-picker (see exports field in /path/to/node_modules/@danielmoncada/angular-datetime-picker/package.json)

./applications/browser/src/styles.scss?ngGlobalStyle - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Package path ./assets/style/picker.min.css is not exported from package /path/to/node_modules/@danielmoncada/angular-datetime-picker (see exports field in /path/to/node_modules/@danielmoncada/angular-datetime-picker/package.json)
```

**Comment by danielmoncada** [comment]
v15 now published: https://www.npmjs.com/package/@danielmoncada/angular-datetime-picker/v/15.0.0

**Comment by KeithGillette** [comment]
@danielmoncada — I still get [the Angular CLI errors I previously reported](https://github.com/danielmoncada/date-time-picker/issues/172#issuecomment-1336181486) when trying to build a project with Angular 15.0.2 and `@danielmoncada/angular-datetime-picker@15.0.0`. Here is the relevant entry from `src/styles.scss`:

```
@import '@danielmoncada/angular-datetime-picker/assets/style/picker.min.css';
```

**Comment by jtc10005** [comment]
I was getting the same error, but I removed node_modules and package,lock.json.  After doing a fresh npm install it worked for me.  The only difference I see is I am doing `@forward "@danielmoncada/angular-datetime-picker/assets/style/picker.min.css";`

**Comment by KeithGillette** [comment]
I am still experiencing [the CSS import build error](https://github.com/danielmoncada/date-time-picker/issues/172#issuecomment-1336181486) with Angular 15.0.4. I have isolated the incompatibility to `@angular-devkit/build-angular@^15.0.0`, which is used by Nx in our monorepository. I'm assuming this has something to do with the changes to SASS and CSS handling noted in the `@angular-devkit/build-angular` section of [the release notes](https://github.com/angular/angular-cli/releases/tag/15.0.0).
