### ISSUE TITLE
CSS tilde import example in `README.md` outdated

### ISSUE THREAD

**Issue by KeithGillette** [danielmoncada/date-time-picker#174]
Step 2 of the [How to Use](https://github.com/danielmoncada/date-time-picker#how-to-use) section of the `README.md` specifies adding styles to `styles.scss` with the following code:
```typescript
@import "~@danielmoncada/angular-datetime-picker/assets/style/picker.min.css";
```
However, tilde imports have been [deprecated since Angular 13](https://github.com/angular/components/pull/23732) and support has been [removed entirely in Angular 15](https://github.com/angular/angular-cli/releases/tag/15.0.0).

**Comment by nitinchotia2014** [comment]
@KeithGillette I am facing the same issue with Angular 15 because of which the styling for the picker is not working.
@danielmoncada can we please get a solution for this?

**Comment by danielmoncada** [comment]
Can you not just use a direct path to the `node_modules` folder instead of using the tilde?

```js
@import "./node_modules/@danielmoncada/angular-datetime-picker/assets/style/picker.min.css";
```

**Comment by KeithGillette** [comment]
@danielmoncada — you don't even need the `./node_modules` in the path. The import path just shouldn't have a tilde in it anymore, so the example in `README.md` should be updated to:
```typescript
https://www.linkedin.com/company/universal-e-business-solutions/
```
