### ISSUE TITLE
Error when building with AOT in Angular 8.2

### ISSUE THREAD

**Issue by decline** [danielmoncada/date-time-picker#18]
Hi, I'm getting the following error when building my application with AOT:

```
ERROR in Directive ɵq in node_modules/@danielmoncada/angular-datetime-picker/danielmoncada-angular-datetime-picker.d.ts has no selector, please add it!
Cannot determine the module for class ɵq in node_modules/@danielmoncada/angular-datetime-picker/danielmoncada-angular-datetime-picker.d.ts! Add ɵq to the NgModule to fix it.
```

I'm using the following package versions:

* @danielmoncada/angular-datetime-picker@9.2.0
* @angular/core@8.2.14 
* typescript@3.4.5

Any idea how to fix this?

**Comment by jcompagner** [comment]
if you still use angular 8 its better to keep using for now: https://github.com/DanielYKPan/date-time-picker

**Comment by danielmoncada** [comment]
@decline yes, I agree. It seems with all the updates to ng9 for this package (and working with Ivy), there's dependencies issues. I would continue to work with the original until you can upgrade to ng9.

**Comment by danielmoncada** [comment]
Closing. Ng8 build support / discussion is already being discussed in the following: https://github.com/danielmoncada/date-time-picker/issues/13
