### ISSUE TITLE
Problems while migrating to Angular 17.3.2

### ISSUE THREAD

**Issue by Robin-Bley** [danielmoncada/date-time-picker#194]
I used the date-time-picker already in Angular 17, but after an update to Angular 17.3.2 the popup does not work.

This is a part of an stacktrace of multiple errors:

```
TypeError: Cannot read properties of null (reading 'clampDate')
    at set pickerMoment (danielmoncada-angular-datetime-picker.mjs:2723:59)
    at OwlDateTimeContainerComponent.initPicker (danielmoncada-angular-datetime-picker.mjs:2959:26)
    at OwlDateTimeContainerComponent.ngAfterContentInit (danielmoncada-angular-datetime-picker.mjs:2817:14)
```

It seems that the DateTimeAdapter could not be found. But when i inject a DateTimeAdapter in my component, it can be injected.

I am using the component in a standalone component. 

These imports are already included: 
- OwlDateTimeModule
- OwlNativeDateTimeModule
- MatDatepickerModule
- MatNativeDateModule

Many thanks in advance.

**Comment by firashamila33** [comment]
can you share an example on how to reproduce ?

**Comment by danielmoncada** [comment]
@Robin-Bley this still an issue?

**Comment by Robin-Bley** [comment]
> @Robin-Bley this still an issue?

Hi @danielmoncada the problem no longer occurs. Thank you very much!
