### ISSUE TITLE
Error: Target entry-point has missing dependencies

### ISSUE THREAD

**Issue by Avejack** [danielmoncada/date-time-picker#20]
Hey I tried to use this package with the native Adapter (instead of the moment adapter) but with Angular 9 (the ivy renderer) I get this error when trying to ng serve my project:

```
ERROR in The target entry-point "@danielmoncada/angular-datetime-picker" has missing dependencies:
 - moment
```

So I guess even though I don't import the moment adapter your package still suggests that it depends on momentjs?

My implementation:
```ts
import { NgModule } from '@angular/core';
import { OwlDateTimeModule, OwlNativeDateTimeModule } from '@danielmoncada/angular-datetime-picker';

import { SharedModule } from '../../shared.module';
import { DatepickerComponent } from './datepicker.component';

@NgModule({
  declarations: [
    DatepickerComponent
  ],
  imports: [
    SharedModule,
    OwlDateTimeModule,
    OwlNativeDateTimeModule,
  ],
  exports: [
    DatepickerComponent
  ]
})
export class DatepickerModule { }
```

In the template:
```html
<input [owlDateTime]="datepicker">
<owl-date-time #datepicker></owl-date-time>
```

**Comment by danielmoncada** [comment]
@Avejack yes. That's because the package itself also come with the Moment adapter (along with the Native adapter) you are using. The original author had first separated these, but decided to add the adapters as part of the actual data/time picker package (I'm assuming for ease / maintainability).

**Comment by Avejack** [comment]
Do you plan to remove this behavior in the future? I mean not the moment adapter but the dependency for it even though i don't want to use momentjs in my project?

Angular seems to be able to do it too since they have the same structure with the native and moment adapters but I am not forced to add momentjs to my dependencies if I don't want to use momentjs.

**Comment by danielmoncada** [comment]
@Avejack , yeah, I'll flag that is a todo.

Feel free to make a PR if you want to take a look 👍

**Comment by Avejack** [comment]
nvm, the Angular Material Team has both Adapters separated as well.

This is the import structure:

```ts
import { MatDatepickerModule } from '@angular/material/datepicker';
import { MatNativeDateModule } from '@angular/material/core';
import { MatMomentDateModule } from '@angular/material-moment-adapter';
```

Since normally you only install @angular/material there is no dependency of momentjs. As soon as you use the @angular/material-moment-adapter package momentjs gets a dependency.

Would be nice if this package would handle it the same way but I can understand that it could be annoying to maintain two separate packages...

**Comment by AndersTornkvist** [comment]
What about using a secondary entry point for the moment adapter? https://github.com/ng-packagr/ng-packagr/blob/master/docs/secondary-entrypoints.md I am afraid this wouldn't be backward compatible, since the moment adapter import would need to be updated to the secondary entry point, i.e. `import { OwlMomentDateTimeModule } from '@danielmoncada/angular-datetime-picker';` would need to be updated to `import { OwlMomentDateTimeModule } from '@danielmoncada/angular-datetime-picker/moment';` in consumer libraries.

**Comment by petemcwilliams** [comment]
As a workaround including moment as a dev dependency does not raise the error

npm install moment --save-dev

**Comment by xavierclotet** [comment]
we don't want to install moment if we don't use it. Please fix it if you can.

**Comment by petemcwilliams** [comment]
That's a separate issue, but you might have some luck with the following.

```
import { DateTimeAdapter } from '@danielmoncada/angular-datetime-picker';

...

   constructor(
...
        private _dateTimeAdapter: DateTimeAdapter<Date>,
...
    ) {
        this._dateTimeAdapter.setLocale(this.getUsersLocale('en-ES'));
    }

```

**Comment by ioiste** [comment]
Are there any plans in the near future to fix this problem? I really wanted to use this without moment.

**Comment by ray-kay** [comment]
Any update on this issue. Serving and building only works when adding Moment which we don't want/need.

And this is how the prod build looks like - Moment takes at least 1/3. I know there ways to exclude all the languages but better would be not having moment at all when using the OwlNativeDateTimeModule.

I was assuming from the documentation there is need of moment when using OwlNativeDateTimeModule but sadly thats not true.


![image](https://user-images.githubusercontent.com/12802386/87424737-c4981680-c5dc-11ea-8bc8-7e906c59bcb9.png)

**Comment by Crocsx** [comment]
Coming to this library since the "original" one is now not compatible anymore. Surprised this is still an issue a year later :/

**Comment by danielmoncada** [comment]
Okay.. finally had time to remove the MomentAdapter, and extract it out into a separate project.

This is in the latest version (https://github.com/danielmoncada/date-time-picker/pull/143) v13.1.0.

If anyone does need a MomentJs adapter, you can find it here [npm](https://www.npmjs.com/package/@danielmoncada/angular-datetime-picker-moment-adapter) or [GitHub](https://github.com/danielmoncada/date-time-picker-moment-adapter).
