### ISSUE TITLE
Some help needed I upgraded a product to Angular 18.0.3 and there is a peer dependency

### ISSUE THREAD

**Issue by lkovari** [danielmoncada/date-time-picker#201]
Hi,

I would appreciate if you help me.
When I would update from 17 to 18 an angular project I faced with the following:

npm error Could not resolve dependency:
npm error peer @angular/common@"^17.0.0" from @danielmoncada/angular-datetime-picker@17.0.0
npm error node_modules/@danielmoncada/angular-datetime-picker
npm error   @danielmoncada/angular-datetime-picker@"^17.0.0" from the root project

Could you please notify me when you updated your package?

**Comment by T4toh** [comment]
The package still works on 18, you can force the update (I did that last week). There is a PR with the update [here](https://github.com/danielmoncada/date-time-picker/pull/199).

**Comment by lkovari** [comment]
Hi

I think the force is not the best solution. Because if you delete
node_modules and run npm install you need to use again the —force which not
recommended.

Can see in the following article about what did the —force
https://weekendprojects.dev/posts/how-to-use-npm-legacy-peer-deps-command/#should-i-use-the---force-flag-or---legacy-peer-deps-flag


L. Kővári

**Comment by T4toh** [comment]
I never said that it was a solution, just possible. If you need to update (like in my case) you can, that's all.

**Comment by LesanuNicolas** [comment]
@danielmoncada can you please look into this pull request posted by NetWin: https://github.com/danielmoncada/date-time-picker/pull/199 , would solve our issues :)

**Comment by NetWin** [comment]
FYI i published the library with angular 18 support.

See: https://github.com/danielmoncada/date-time-picker/pull/199#issuecomment-2195436851

**Comment by danielmoncada** [comment]
@LesanuNicolas  published
