### ISSUE TITLE
Date Formatting Issues

### ISSUE THREAD

**Issue by sasmj** [danielmoncada/date-time-picker#28]
The question below was originally posted on https://github.com/DanielYKPan/date-time-picker/issues/687, but I'm guessing that's now dead. Some comments in the project, led me here. Any help would be greatly appreciated. 

We are on Angular version 6.

I've been stuck on the following issues for a while now and not sure what else to try. I need a the date time format to be in yyyy-MM-dd HH:mm. I have followed the instructions in https://danielykpan.github.io/date-time-picker/#locale-formats and I have added the imports, MY_NATIVE_FORMATS and the providers to to my app.module.ts file as follows:

```ts
import { DateTimeAdapter, OwlDateTimeModule, OwlNativeDateTimeModule, OWL_DATE_TIME_LOCALE, OWL_DATE_TIME_FORMATS } from 'ng-pick-datetime';

export const MY_NATIVE_FORMATS = {

fullPickerInput: 'yyyy-MM-dd HH:mm'

}

imports: [
OwlDateTimeModule,
OwlNativeDateTimeModule
],
providers: [
{provide: OWL_DATE_TIME_LOCALE, useValue: 'en-GB'},
{provide: OWL_DATE_TIME_FORMATS, useValue: MY_NATIVE_FORMATS.fullPickerInput}
]
```

With the above in place, the problem I have, is that all datetimepickers display the date only with format dd/MM/YYYY with no time component at all. So for example Monday 16th March 2020 11:20 will simply display as 16/03/2020 instead of 2020-03-16 11:20.

The second issue I have is that when I use the date picker, the format of the date is different to when I type a date into the field directly, which seems to only accept dates in the format of mm/dd/yyyy.

The third issue, as advised by DanielYKPan, when I try to create a custom-date-picker.ts and extend DateTimeAdapter, I have to implement many abstract members defined in DateTimeAdapter.

Any help is appreciated.

Thanks

**Comment by danielmoncada** [comment]
@sasmj what's the update on this issue?

I'm able to get the date format you want, simply by setting only the 'local'. No need to provide a custom date/time format, as the local already uses the format you want.

```ts
  providers: [
   { provide: OWL_DATE_TIME_LOCALE, useValue: 'en-GB' }
  ],
```

**Comment by vikaspathneja** [comment]
Same issue i am facing using MOMENT_FORMAT 
*****below code are of my module*****  

export const MY_MOMENT_FORMATS = {
	parseInput: 'LLL',
	fullPickerInput: 'LLL',
	datePickerInput: 'DD/MM/YYYY hh:mm:ss A',
	timePickerInput: 'LT',
	monthYearLabel: 'YYYY',
	dateA11yLabel: 'LL',
	monthYearA11yLabel: 'YYYY',
};

 { provide: OWL_DATE_TIME_FORMATS, useValue: MY_MOMENT_FORMATS },

**Comment by Lempkin** [comment]
Hi,

@danielmoncada  I'm guessing ng-pick-datetime-moment is not compatible with Angular 9+ Ivy ? 
I've tried to add it as dependency and import it in main module and I got some errors : 

> ERROR in node_modules/ng-pick-datetime-moment/node_modules/@angular/core/src/linker/compiler.d.ts:71:25 - error TS2694: Namespace '"C:/Users/.../Documents/Git/cerebra/src/WebApp/ClientApp/node_modules/ng-pick-datetime-moment/node_modules/@angular/core/src/r3_symbols"' has no exported member 'ɵɵFactoryDef'.
>     
>     71     static ɵfac: ɵngcc0.ɵɵFactoryDef<Compiler, never>;

**Comment by danielmoncada** [comment]
@Lempkin this is correct. ```ng-pick-datetime-moment``` package should not be used with this package (this was for the old version). This package already provides its own moment adapter with it.

**Comment by sasmj** [comment]
sorry. I got pulled off the project mid way, so unable to say what the
resolution was.

Thanks

**Comment by danielmoncada** [comment]
closing, as appears OP has fixed the issue / no longer has a problem
