### ISSUE TITLE
Scroll strategies

### ISSUE THREAD

**Issue by newsash** [danielmoncada/date-time-picker#29]
Could you please make `overlay` in the `OwlDateTimeComponent` public?
https://github.com/danielmoncada/date-time-picker/blob/master/projects/picker/src/lib/date-time/date-time-picker.component.ts#L298

Use case:
`<owl-date-time #dt [scrollStrategy]="dt.overlay.scrollStrategies.reposition()"></owl-date-time>`

**Comment by danielmoncada** [comment]
@newsash yeah I'll do that

**Comment by danielmoncada** [comment]
See https://github.com/danielmoncada/date-time-picker/pull/30
