### ISSUE TITLE
 Typo in example

### ISSUE THREAD

**Issue by BO41** [danielmoncada/date-time-picker#36]
On https://daniel-projects.firebaseapp.com/owlng/date-time-picker/#locale-formats at the second example there is a typo:
```ts
constructor(dateTimeAdapter: DateTimeAdapter<any>) {
    dateAdapter.setLocale('ja-JP'); // change locale to Japanese
}
```

`dateAdapter` should be `dateTimeAdapter` as declared above

**Comment by danielmoncada** [comment]
thanks for the submission. Unfortunately, i do not have access to the original author's demo code that is hosted on firebase, so any issues there cannot be changed.

**Comment by danielmoncada** [comment]
Closing, as this cannot be fixed. If time permits, a new hosted demo with this fork should be done.
