### ISSUE TITLE
Using dayjs for date-time-adapter

### ISSUE THREAD

**Issue by qwe12e** [danielmoncada/date-time-picker#38]
Currently i created a date-time-adapter with dayjs and i want to remove moment. I'm not using moment-adapter but while building the project it gives me error.

![image](https://user-images.githubusercontent.com/13543079/80224854-f9867400-8652-11ea-9b24-17f8e32b8feb.png)

Can you make moment-adapter optional package like material' date-picker did.

**Comment by danielmoncada** [comment]
There's an issue open to resolve the moment dependency if it is not being used.

See https://github.com/danielmoncada/date-time-picker/issues/20
