### ISSUE TITLE
Issue When mulitple date picker in same screen

### ISSUE THREAD

**Issue by dhavalsolankislk** [danielmoncada/date-time-picker#39]
Hello,
We are using date picker in our application. We are facing problem when our screen height is small

Our normal screen with two date picker is 
![Capture1](https://user-images.githubusercontent.com/59446200/81272049-8e816800-906a-11ea-9f7c-199eba22697d.PNG)

Here when we click on left side date picker date picker opens as shown below
![Capture2](https://user-images.githubusercontent.com/59446200/81272196-d0121300-906a-11ea-86ab-1f31b16e31fa.PNG)

But when we click on right side date picker, the date picker opens down side and date picker's bottom part is getting cut 

![Capture3](https://user-images.githubusercontent.com/59446200/81272397-110a2780-906b-11ea-8b11-874fd73a3bcf.PNG)

Can you help me with the issue.

**Comment by danielmoncada** [comment]
@dhavalsolankislk the date/time picker has a 'scroll strategy' that should be set. 

See: https://github.com/DanielYKPan/date-time-picker/issues/414

**Comment by dhavalsolankislk** [comment]
Hello,
@danielmoncada 
This is not working in my scenario

**Comment by danielmoncada** [comment]
@dhavalsolankislk why does this not work for your scenario? also, have you tried setting the top / left position for it?

**Comment by dhavalsolankislk** [comment]
@danielmoncada 
I tried with above scenario but its not working

**Comment by dhavalsolankislk** [comment]
@danielmoncada  Any update ?
