### ISSUE TITLE
Pophover close when selecting date inside the pophover

### ISSUE THREAD

**Issue by dhavalsolankislk** [danielmoncada/date-time-picker#40]
Hello,
We are using ngbPopover as pop-box.
And inside pop-box we put Date picker
On click of date picker open date selection pop box then selection of date main popbox is close.

Here in popHover we have added properties [autoClose]="'outside'"
Issue : On selection of date in date picker not close main popover box.

![Capture4](https://user-images.githubusercontent.com/59446200/81274728-4fedac80-906e-11ea-9369-b0fdc61249d0.PNG)

Versions of ng-bootstrap ,Bootstrap and Angular Date Time Picker:
"@danielmoncada/angular-datetime-picker": "^9.3.0"
"@ng-bootstrap/ng-bootstrap": "^6.1.0"
"bootstrap": "^4.4.1"

**Comment by danielmoncada** [comment]
> Issue : On selection of date in date picker not close main popover box.

So, the issue here is when you select a date from the date/time picker, you want the popbox to close? Is this correct?

**Comment by dhavalsolankislk** [comment]
@danielmoncada 

We don't want to close the popbox. In our case it is closing popbox.

**Comment by danielmoncada** [comment]
@dhavalsolankislk sounds like this might be an issue with the popup box itself. The reason why it's closing is because the date/time picker is a separate popup box / container. When you are clicking it, you are essentially 'leaving' the popup box, hence the closing. Does the popup box have some type of event you can override so that you can ignore the close if the clicked element is the date/time picker?

**Comment by danielmoncada** [comment]
@dhavalsolankislk  looking at their documentation:

https://ng-bootstrap.github.io/#/components/popover/examples

You will need to set manual open/close. From there, have an event listener for your popup where if you click outside it AND if it's not the date/time picker, then you do a manual close.

There are many ways to determine whether you've clicked outside your div in the popup. Here's one: [https://stackoverflow.com/questions/40107008/detect-click-outside-angular-component/59234391#59234391](url)

**Comment by danielmoncada** [comment]
Closing as this is not an issue with the date/time control itself, but an issue on how it's used with the pop up control OP has integrated. I've provided a solution in the comments above.
