### ISSUE TITLE
Close Date Picker on click of enter button 

### ISSUE THREAD

**Issue by dhavalsolankislk** [danielmoncada/date-time-picker#45]
Hello,
We are using owl date picker picker. We want a functionality in which we want to close date picker on press enter key which is not provided.

**Comment by dhavalsolankislk** [comment]
@danielmoncada 
Issue Updated and new issue added https://github.com/danielmoncada/date-time-picker/issues/47

**Comment by danielmoncada** [comment]
@dhavalsolankislk  there is already board focusing when [enter] is pressed. For example, if the date picker is opened, and you press [enter]  this will select the day in which you can then move the date selection / range with the arrow keys.

At which point do you want [enter] to close the picker? I do  not want to take away from the current [enter] behavior.

**Comment by dhavalsolankislk** [comment]
@danielmoncada 
When we press [esc], the date/time picker will close but value will not set in text field

**Comment by danielmoncada** [comment]
@dhavalsolankislk sorry, going to close this. pressing [**enter**] already has it's own built in functionality, as it allows the user to select the date/time range (either min or both min / max). From there, if they want to use [**enter**] to set the field, they will need to [**tab**] over to the set button then press [**enter**].
