### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by rogyvoje** [danielmoncada/date-time-picker#48]
Hey guys,

Happy to see someone is going to maintain the library :smile_cat: 

I just wanted to know why is `moment` required as a library?

If I don't have install moment I get the following error:

```
ERROR in The target entry-point "@danielmoncada/angular-datetime-picker" has missing dependencies:
 - moment
```

**Comment by danielmoncada** [comment]
Hey @rogyvoje the reason being is that the original author added the moment adapter as part of the package (I'm assuming so that he doesn't have to maintain two different packages). There's a discussion about it here: https://github.com/danielmoncada/date-time-picker/issues/20

**Comment by rogyvoje** [comment]
I understand but take a look at my pull request.
https://github.com/danielmoncada/date-time-picker/pull/49

Is it possible to exclude it, as anyone can write their own implementation for moment?

Maybe we can add additional section in README.md to reference moment adapter which anyone can copy to their own project. Or is there any better way to do this as I don't really need moment.
