### ISSUE TITLE
build with production mode fails

### ISSUE THREAD

**Issue by vikaspathneja** [danielmoncada/date-time-picker#55]
when building with production mode giving issues, while building without production is running fine
* Command Used: **ng build --prod**

**Enviornment Versions:** 
node v12.16.2
npm  v6.14.4

**Dependencies Version:**
angular/core": "^8.2.14",
angular/material": "^8.2.3",
angular/material-moment-adapter": "^9.2.0",
moment": "^2.27.0",
**ng-pick-datetime": "^7.0.0",
ngx-bootstrap": "^4.2.0",

---tried both version 1.0.7 ,1.0.8 one by one for testing --------
**ng-pick-datetime-moment": "^1.0.8",****
**ng-pick-datetime-moment": "^1.0.7",****

----------------import statements used in my module----------------------------------
import { DateTimeAdapter, OWL_DATE_TIME_LOCALE, OwlDateTimeIntl } from 'ng-pick-datetime';
import { MomentDateTimeAdapter } from 'ng-pick-datetime-moment';

**Tried importing  OwlMomentDateTimeModule**  by both ways ,but both not working in my module--------
// import { OwlMomentDateTimeModule } from 'ng-pick-datetime-moment';
import { OwlMomentDateTimeModule } from 'ng-pick-datetime/date-time/adapter/moment-adapter/moment-date-
time.module';

import { OwlDateTimeModule, OwlNativeDateTimeModule, OWL_DATE_TIME_FORMATS } from 'ng-pick-datetime';

**ERROR in ../ng-pick-datetime-moment/moment-adapter/moment-date-time-adapter.class.ts(46,2): Error during template compile of 'MomentDateTimeAdapter'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'Injectable'
    'Injectable' calls 'ɵmakeDecorator'.**

**Comment by vikaspathneja** [comment]
**Attached Zip**
module typescript file
package json file

[PackageJsonAndModuleFile.zip](https://github.com/danielmoncada/date-time-picker/files/4845161/PackageJsonAndModuleFile.zip)

**Comment by vikaspathneja** [comment]
@danielmoncada  Please Check as it is important for making build for production server, waiting for positive response

**Comment by danielmoncada** [comment]
@vikaspathneja still an issue? if not, going to close this

**Comment by vikaspathneja** [comment]
Can you please tell whether you package is supporting angular 8 or only
angular 9+

Vikas
Email: vikas42329@gmail.com
Mobile: +91 9467709200
[image: linkedin icon] <https://in.linkedin.com/in/vikaspathneja> [image:
twitter icon] <https://twitter.com/vikas42329>[image: facebook icon]
<https://www.facebook.com/vikaspathneja>

**Comment by danielmoncada** [comment]
@vikaspathneja ng9.

Per docs:

**The date/time picker has been updated to support Angular 9, as well as compilation using Ivy.
If you need Ng8 support, please stick with: https://github.com/DanielYKPan/date-time-picker**
