### ISSUE TITLE
Using Angular Material v10 

### ISSUE THREAD

**Issue by thorsten** [danielmoncada/date-time-picker#56]
We updated our project to Angular v10 and upgrading Angular Material v10 didn't work without using --force:

```
$ ng update @angular/material
Using package manager: 'npm'
Collecting installed dependencies...
Found 40 dependencies.
Fetching dependency metadata from registry...
                  Package "@danielmoncada/angular-datetime-picker" has an incompatible peer dependency to "@angular/cdk" (requires "^8.0.0 || ^9.0.0", would install "10.0.1").
✖ Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
  See "/private/var/folders/9w/p0dbd93j26qcc_5z4h222_c00000gn/T/ng-kqHLjM/angular-errors.log" for further details.
```

The update with --force worked without any issues.

**Comment by jcompagner** [comment]
i wonder if it is possible to be a bit more lenient in upwards compatibility 
Can't a component just say i need minimum this version and leave it to the user to go up?
Yes that could potentially break something if a dependency did do a breaking change.

**Comment by danielmoncada** [comment]
I've been pretty busy with work lately.. I'll do my best to look into ng10 support this week

**Comment by Londeren** [comment]
@danielmoncada please, let us know when you can add support for ng 10

**Comment by danielmoncada** [comment]
@thorsten @jcompagner @Londeren I've made an alpha version for ng10. if you have time, please try it out and let me know if there are any issues before a fully release it: 

https://www.npmjs.com/package/@danielmoncada/angular-datetime-picker/v/10.0.0-alpha.0

**Comment by fruchtzwerg** [comment]
Working on the same project as @thorsten.
@danielmoncada I've used your alpha version to update angular to the latest v10 patch version. Worked without issues.

**Comment by danielmoncada** [comment]
@fruchtzwerg thanks, I'll go ahead and push it out of alpha.
