### ISSUE TITLE
"disabled" attribute with compilation error on angular 9 with fullTemplateTypeCheck option

### ISSUE THREAD

**Issue by POFerro** [danielmoncada/date-time-picker#58]
Hi,

As in #46 same behaviour happens with disabled attribute.
I believe these properties should have type of string | boolean and setter should be handled with angular coerceBooleanProperty(stringOrBoolean) to take care of the variations of value.

Thanks in advance and best regards :)
POFerro

**Comment by danielmoncada** [comment]
@POFerro are there any other attributes that you need added?

**Comment by danielmoncada** [comment]
closing, no update > 1 year
