### ISSUE TITLE
How to disable validation while inputing time and minute

### ISSUE THREAD

**Issue by Blair2004** [danielmoncada/date-time-picker#60]
Hi, 
I'm currently using the version 9.4.2, and the issue I'm facing is that when we're retrying to input an hour and minutes over the time fields, someone there is a validation running making it impossible to set time like 12, 15, as for the first number entered, it's immediately led by a 0.

![Peek 2020-07-04 18-48](https://user-images.githubusercontent.com/5265663/86518155-f8c64700-be26-11ea-8a4f-9b9c3589eef0.gif)

This is really annoying as we don't necessarily need to use the arrows

**Comment by Blair2004** [comment]
I don't know who created that feature, but it's so annoying.

**Comment by danielmoncada** [comment]
@Blair2004 yeah not sure who added this. must have been done by the original author. I'll look into it

**Comment by Blair2004** [comment]
Thank you 😊

On Jul 5, 2020 11:19 PM, "Daniel Moncada" <notifications@github.com> wrote:

@Blair2004 <https://github.com/Blair2004> yeah not sure who added this.
must have been done by the original author. I'll look into it

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/danielmoncada/date-time-picker/issues/60#issuecomment-653946022>,
or unsubscribe

**Comment by danielmoncada** [comment]
@Blair2004 found the issue. For some reason there's a Pipe bound to automatically make it 2 digits. Need to figure out if removing it will cause other issues (outside of formatting).

**Comment by Dovlus** [comment]
The reason it was working fine before is that debounce for input field value change was set to 500ms which was enough time to type in both digits.
Debounce time was changed to 1ms in order to fix issue #34.

**Comment by danielmoncada** [comment]
@Dovlus right, though I feel that the debounce simply hid the initial issue. Looking to an alternate solution

**Comment by danielmoncada** [comment]
fixed in https://github.com/danielmoncada/date-time-picker/pull/63
