### ISSUE TITLE
Time-picker problem inside bootstrap modal

### ISSUE THREAD

**Issue by Alex-Simple-Fly** [danielmoncada/date-time-picker#61]
Hi, I am having an issue with time-picker when I am trying to implement it in a bootstrap modal. 
Like said in that issue 
https://github.com/DanielYKPan/date-time-picker/issues/372

I'm overwritten the css z-index for class cdk-overlay-container, but inputs for minutes and hours are not accessible, the user can only click the arrows.

Maybe anyone know's fix for that problem?

**Comment by developerGM** [comment]
I have the same problem.

**Comment by chiangs** [comment]
Are you using the hasBackdrop: true in the OverlayConfig? Try turning it false if you can access the config.

**Comment by developerGM** [comment]
Where is this config?

**Comment by chiangs** [comment]
It's part of the cdk overlay config but it's possible that it is not exposed to you

**Comment by developerGM** [comment]
yes, confirm, this is not exposed. So how can we solve this problem?

**Comment by developerGM** [comment]
I am trying to change (only for test) this file date-time-picker.component in this part as this:
`OwlDateTimeComponent.prototype.createPopup = function () {
        var _this = this;
        var overlayConfig = new OverlayConfig({
            positionStrategy: this.createPopupPositionStrategy(),
            hasBackdrop: false,
            backdropClass: ['cdk-overlay-transparent-backdrop'].concat(coerceArray(this.backdropClass)),
            scrollStrategy: this.scrollStrategy || this.defaultScrollStrategy(),
            panelClass: ['owl-dt-popup'].concat(coerceArray(this.panelClass)),
        });
        this.popupRef = this.overlay.create(overlayConfig);
        merge(this.popupRef.backdropClick(), this.popupRef.detachments(), this.popupRef.keydownEvents().pipe(filter(function (event) { return event.keyCode === ESCAPE ||
            (_this._dtInput && event.altKey && event.keyCode === UP_ARROW); }))).subscribe(function () { return _this.close(); });
    };`

but this not solve the problem

**Comment by developerGM** [comment]
I solved changing this
`<div class="modal fade" id="modalCalendar" tabindex="-1" role="dialog" aria-hidden="true">`

whit this
`<div class="modal fade" id="modalCalendar" role="dialog" aria-hidden="true">`

**Comment by danielmoncada** [comment]
OP found a solution. see https://github.com/danielmoncada/date-time-picker/issues/61#issuecomment-694489985
