### ISSUE TITLE
Setting OWL_DATE_TIME_FORMATS custom formats does not work

### ISSUE THREAD

**Issue by eladco898** [danielmoncada/date-time-picker#62]
Hi,
I have tried to set a custom moment formats in my app.module.ts but it does not work.
Can someone provide a working example(maybe in a plunker) of OWL_DATE_TIME_FORMATS for Angular9?

Thanks

**Comment by ZeSzymi** [comment]
you have to provide the locale in app.module

```
import localeNb from '@angular/common/locales/nb';
import localeNbExtra from '@angular/common/locales/extra/nb';
import { registerLocaleData } from '@angular/common';

registerLocaleData(localeNb, localeNbExtra);
```

**Comment by danielmoncada** [comment]
@eladco898  is this an issue? Did you try what @ZeSzymi  recommended?

**Comment by eladco898** [comment]
No.
You can close this issue
