### ISSUE TITLE
Date & time picker write 13 in minutes textbox but when 1 enter auto trigger and add 01

### ISSUE THREAD

**Issue by rohit64Singh222** [danielmoncada/date-time-picker#64]
Hello,

I am using data & time picker but problem created when enter manually minutes textbox. If enter 13 then press 1 and automatic trigger and 01 in minute textbox.

![image](https://user-images.githubusercontent.com/57747188/87938331-0d0b7480-cab4-11ea-9de4-c344e1827164.png)

Solution : Provide solution for not auto add 0 in minute textbox.

**Comment by danielmoncada** [comment]
which version are you using? this was fixed in: https://github.com/danielmoncada/date-time-picker/issues/60

**Comment by danielmoncada** [comment]
This was fixed. Closing
