### ISSUE TITLE
main property on package.json should be es2015

### ISSUE THREAD

**Issue by jpike88** [danielmoncada/date-time-picker#68]
Angular 10 is not compatible with esm5, fesm5 bundles.

This library has this as the main property in its package.json, and it's causing issues in an angular 10 build. in the meantime I have to use an alias to force the es2015 bundle instead

```"main": "bundles/danielmoncada-angular-datetime-picker.umd.js",```

Should have this value instead:
```fesm2015/danielmoncada-angular-datetime-picker.js```

**Comment by danielmoncada** [comment]
@jpike88  I've made an alpha version for ng10. if you have time, please try it out and let me know if there are any issues before a fully release it: 

https://www.npmjs.com/package/@danielmoncada/angular-datetime-picker/v/10.0.0-alpha.0

**Comment by jpike88** [comment]
confirmed working, thanks
