### ISSUE TITLE
Display UTC

### ISSUE THREAD

**Issue by wwjd1234** [danielmoncada/date-time-picker#71]
How can we display UTC format instead of the GMT time?

**Comment by danielmoncada** [comment]
@wwjd1234  are you using moment?

**Comment by danielmoncada** [comment]
@wwjd1234 any updates on this?

**Comment by wwjd1234** [comment]
Yes I am using moment. It seems if I use UTC the browser converts it to local time for viewing, but once I read/set the date it is back to UTC. Same in the reverse, if I use local time but the browser displays in UTC then when I read/set I get local time not UTC. Is there. Way to have UTC be set in code and for display. Any ideas or code examples would be helpful.

**Comment by danielmoncada** [comment]
stale, closing
