### ISSUE TITLE
Errors in node_modules date-time-moment

### ISSUE THREAD

**Issue by wwjd1234** [danielmoncada/date-time-picker#73]
After doing npm install ng-pick-datetime-moment moment --save;

I get the following errors

ERROR in ./node_modules/ng-pick-datetime-moment/__ivy_ngcc__/moment-adapter/moment-date-time-adapter.class.js 231:30-55
"export 'ɵɵdefineInjectable' (imported as 'ɵngcc0') was not found in '@angular/core'
ERROR in ./node_modules/ng-pick-datetime-moment/__ivy_ngcc__/moment-adapter/moment-date-time.module.js 16:28-51
"export 'ɵɵdefineInjector' (imported as 'ɵngcc0') was not found in '@angular/core'
ERROR in ./node_modules/ng-pick-datetime-moment/__ivy_ngcc__/moment-adapter/moment-date-time.module.js 43:31-54
"export 'ɵɵdefineInjector' (imported as 'ɵngcc0') was not found in '@angular/core'
ERROR in ./node_modules/ng-pick-datetime-moment/__ivy_ngcc__/moment-adapter/moment-date-time.module.js 15:28-51
"export 'ɵɵdefineNgModule' (imported as 'ɵngcc0') was not found in '@angular/core'
ERROR in ./node_modules/ng-pick-datetime-moment/__ivy_ngcc__/moment-adapter/moment-date-time.module.js 42:31-54
"export 'ɵɵdefineNgModule' (imported as 'ɵngcc0') was not found in '@angular/core'
ERROR in ./node_modules/ng-pick-datetime-moment/__ivy_ngcc__/moment-adapter/moment-date-time-adapter.class.js 230:113-128
"export 'ɵɵinject' (imported as 'ɵngcc0') was not found in '@angular/core'
ERROR in ./node_modules/ng-pick-datetime-moment/__ivy_ngcc__/moment-adapter/moment-date-time-adapter.class.js 230:155-170
"export 'ɵɵinject' (imported as 'ɵngcc0') was not found in '@angular/core'
ERROR in ./node_modules/ng-pick-datetime-moment/__ivy_ngcc__/moment-adapter/moment-date-time.module.js 44:66-91
"export 'ɵɵsetNgModuleScope' (imported as 'ɵngcc0') was not found in '@angular/core'

**Comment by danielmoncada** [comment]
@wwjd1234 ng version?

**Comment by danielmoncada** [comment]
The issue is that you are using the old ng-pick-datetime-moment adapter npm package. There's no need to use this anymore, as the moment adapter is now built in.
