### ISSUE TITLE
Date Time Range Picker - Changing time in input doesn't reflect

### ISSUE THREAD

**Issue by Ajayachathru** [danielmoncada/date-time-picker#76]
**I'm using Angular, 8 ng-pick-datetime version 7.0.0**

In https://danielykpan.github.io/date-time-picker/ Use with @angular/forms section,

Click Date Time Range Picker, choose same date in from & to
type in from time as 08:00:00
type in to time as 08:15:00

only seconds gets changed as 15, hours not changed !

**Comment by Ajayachathru** [comment]
HI,

can't enter same Hour / Minute / Second in from & to time.

After debugging, Understood the issue in timer-box.component.js
you are maintaining single inputStream for both from and to time.

**distinctUntilChanged()** will not emit when the same value is entered.
we need to remove it or maintain separate streams for from & to time.

please fix this soon in ng-pick-datetime 7.0.0

Issue:
    OwlTimerBoxComponent.prototype.ngOnInit = function () {
        var _this = this;
        this.inputStreamSub = this.inputStream.pipe(debounceTime(500), distinctUntilChanged()).subscribe(function (val) {    
            if (val) {
                var inputValue = coerceNumberProperty(val, 0);
                _this.updateValueViaInput(inputValue);
            }
        });
    };


Fix:
    OwlTimerBoxComponent.prototype.ngOnInit = function () {
        var _this = this;
        this.inputStreamSub = this.inputStream.pipe(debounceTime(500)).subscribe(function (val) {    
            if (val) {
                var inputValue = coerceNumberProperty(val, 0);
                _this.updateValueViaInput(inputValue);
            }
        });
    };

**Comment by danielmoncada** [comment]
@Ajayachathru thanks for your feedback.

I am not maintaining ng-pick-datetime 7.0.0. This current library is forked from that because it was no longer mainted.

I can look into fixing the issue here, as part of @danielmoncada/angular-datetime-picker

**Comment by Ajayachathru** [comment]
@danielmoncada 

sure, thanks :+1:

**Comment by Ajayachathru** [comment]
Hi @danielmoncada 

Have you fixed this issue ?

**Comment by danielmoncada** [comment]
@Ajayachathru  no, I'm busy at work with the moment, so I haven't had a chance. 
Feel free to fix it yourself and make a PR if you want

**Comment by Ajayachathru** [comment]
Hi @danielmoncada 

Okay. I'll fix it and make a PR by tomorrow evening.

**Comment by danielmoncada** [comment]
@Ajayachathru thanks, let me look over the PR. 👍

**Comment by Ajayachathru** [comment]
Hi @danielmoncada .. can you please check and merge this

**Comment by danielmoncada** [comment]
@Ajayachathru taking a look now! thanks

**Comment by danielmoncada** [comment]
@Ajayachathru published! thanks again https://www.npmjs.com/package/@danielmoncada/angular-datetime-picker/v/10.1.0

**Comment by Ajayachathru** [comment]
thanks :) @danielmoncada
