### ISSUE TITLE
Cannot run my app after installing date-time-picker

### ISSUE THREAD

**Issue by ArtzGroup** [danielmoncada/date-time-picker#80]
I tried the installation steps. But, it doesn't compile at all. I just installed it with `npm install @danielmoncada/angular-datetime-picker --save`. I didn't even add it in AppModule yet. Not sure why this happens. Without installing this package, my app is running fine. I am getting this error.

`AggregateException: One or more errors occurred. (One or more errors occurred. (The NPM script 'start' exited without indicating that the Angular CLI was listening for requests. **The error output was: Compiling @danielmoncada/angular-datetime-picker : module as esm5**`

I tried npm audit fix, npm fund. But, nothing works. I am using Angular 9.1. Any idea about this? Thanks in advance.

**Comment by danielmoncada** [comment]
@ArtzGroup do you still have the issue? 
What does your package.json show? Please take a look at https://stackoverflow.com/questions/50221618/the-npm-script-start-exited-without-indicating-that-the-angular-cli-was-listen

I think it's a configuration issue with your NG project and not the package itself

**Comment by ArtzGroup** [comment]
Thank you. It works now. The issue is with my git branches. I am working on multiple branches of same project. When I am running the branch which doesn't use this library, this error occurs. But, when I run the app which uses the library it works fine. Not sure why this happens, but I have to delete and install node_modules every time I change my branches.
