### ISSUE TITLE
There is no option for only Year Selection

### ISSUE THREAD

**Issue by rohit64Singh222** [danielmoncada/date-time-picker#81]
Hello..!
In this Repository there were no option of only selection of year. there were option for year and month both combine but in my project i required only year selection than i post this issue. please provide solution of it.

**Comment by igorlino** [comment]
I think you can use a workaround:
```

<input [owlDateTimeTrigger]="endDateEl" [owlDateTime]="endDateEl" [(ngModel)]="endMonth">
<owl-date-time [pickerType]="'calendar'"
                                       (monthSelected)="yearHandler($event, endDateEl)"
                                       [startView]="'multi-year'" #endDateEl></owl-date-time>

yearHandler(normalizedYear: Date, datepicker: OwlDateTimeComponent<any>) {
        console.log(normalizedYear.getFullYear());
        datepicker.close();
    }
```

You may also hide using CSS the parts of the dialog you dont want to show. For that you will need to turn encapsulation off in the component where you are using the picker.

```
@Component({
    ...
    encapsulation: ViewEncapsulation.None
})
```

**Comment by rohit64Singh222** [comment]
Thanks for reply.

 But when open year piker showing 
![image](https://user-images.githubusercontent.com/57747188/100095654-d8079800-2e80-11eb-9b44-b6c8460c9a2e.png)
![image](https://user-images.githubusercontent.com/57747188/100095874-2d43a980-2e81-11eb-9ea9-37ddfc2b389d.png)


and when click on year open days as bellow 
![image](https://user-images.githubusercontent.com/57747188/100095743-fbcade00-2e80-11eb-8655-ac0fe32ac23b.png)

We only need to show year select and after select show only year, please provide suggestion.

**Comment by igorlino** [comment]
I could in theory extend my pull request to add an option of multiyearOnly

https://github.com/danielmoncada/date-time-picker/issues/94
https://github.com/danielmoncada/date-time-picker/pull/95

I implemented it for month picker.

Its far from 100% perfect, but sufficient for picking up months.

**Comment by igorlino** [comment]
As it was relatively simple I extended my MR https://github.com/danielmoncada/date-time-picker/pull/95.

flat is using:
**[multiyearOnly]="true"**

with it, one can:
```

<input [owlDateTimeTrigger]="yearEl" [owlDateTime]="yearEl" [(ngModel)]="selectedYear">
<owl-date-time [pickerType]="'calendar'"
                                        [multiyearOnly]="true"
                                       (yearSelected)="yearHandler($event, yearEl)"
                                       [startView]="'multi-year'" #yearEl></owl-date-time>

yearHandler(normalizedYear: Date, datepicker: OwlDateTimeComponent<any>) {
        console.log(normalizedYear.getFullYear());
        datepicker.close();
    }
```

You still need to hide using CSS the parts of the dialog you dont want to show. For that you will need to turn encapsulation off in the component where you are using the picker.

```
@Component({
    ...
    encapsulation: ViewEncapsulation.None
})
```

**Comment by danielmoncada** [comment]
@igorlino  thanks for the PR! merged and released.

Check out version 10.2.0 👍
