### ISSUE TITLE
Make YEARS_PER_ROW & YEAR_ROWS  customizable

### ISSUE THREAD

**Issue by Lonli-Lokli** [danielmoncada/date-time-picker#82]
Currently it's constants 

export const YEARS_PER_ROW = 3;
export const YEAR_ROWS = 7;

Could you move them to the options?

**Comment by danielmoncada** [comment]
@Lonli-Lokli  thanks, I'll look over and merge the PR sometime today.

**Comment by danielmoncada** [comment]
@Lonli-Lokli  can you create a new pull request? I initially merged it (should have checked before hand), but there were some issues in the UTs.. I had fixed them, but a bunch are still failing so I went head and reverted the merge.

**Comment by Lonli-Lokli** [comment]
@danielmoncada I know it was in previous year, sorry about that. I've created PR one more time
