### ISSUE TITLE
On installing the date-time-picker

### ISSUE THREAD

**Issue by monis001** [danielmoncada/date-time-picker#86]
Hi, I have an ANgular8+ project and on installing the date-time-picker, it's generating errors. 

![image](https://user-images.githubusercontent.com/46885793/97703287-65500a80-1ad6-11eb-92ee-1ee7a3acd6ff.png)

PS: I believe this repo is actively maintained, and the repo from which is forked seems not maintained, or no communication from maintainers. If anyone could guide.

Thanks

**Comment by jcompagner** [comment]
are you sure we talk here about this date picker?
it seems more that you are using aggrid .. and it complains for that.

**Comment by monis001** [comment]
Hi, That's the folder name, if you will check ut closely it is pointing out in date-picker modules, please check the below image  : 
**Angular (v : 8+)**
![date-picker-2](https://user-images.githubusercontent.com/46885793/97839042-6320c280-1d07-11eb-9c17-284e68b536cf.PNG)

(Yellow box pointing the project path) 

also when tried with **Angular-10**, still showing the error  : 

![date-time-picker-issue](https://user-images.githubusercontent.com/46885793/97839195-ada23f00-1d07-11eb-8e13-a8ddae74ccd0.PNG)

**Comment by jcompagner** [comment]
right i was confused because ng-pick-datetime is not the current package of this product.
but this product has a devDepedency on https://github.com/danielmoncada/date-time-picker/blob/master/package.json#L57 angular/cdk

So it could be that that is just a requirement (in our product we also use that) including also moment

**Comment by danielmoncada** [comment]
@monis001 your first two screenshots are using the wrong package. Package should be @danielmoncada/angular-datetime-picker not ng-pick-datetime.

@jcompagner  is right. In your last screenshot, looks like you're using the correct package but you're missing dev dependencies. you need to install those manually either through NPM or Yarn.

**Comment by igorlino** [comment]
@danielmoncada I also came to the same problem with the cdk dependency, I think it may be a good thing to document it in the README

npm install @angular/cdk --save
npm install @danielmoncada/angular-datetime-picker --save

**Comment by danielmoncada** [comment]
@igorlino good idea. i'll add it next rev. thanks!

**Comment by monis001** [comment]
Yes.... 

After googling came across the missing packages, later installed that.
