### ISSUE TITLE
How can I disable input so user don't type

### ISSUE THREAD

**Issue by Applicafroguy** [danielmoncada/date-time-picker#88]
I have an issue where the user tries to edit or type on the input field. This causes the date to be invalid.

When I do this the `<input />` is disabled it's not clickable

`   <input
              readonly
              [owlDateTimeTrigger]="dt3"
              [owlDateTime]="dt3"
              [disabled]="true"
              formControlName="pickup_time"
              name="pickup_time"
              class="nordex-input placeholder-gray-700"
              id="pickup_time"
              placeholder="9:54 AM"
            />
            <owl-date-time [pickerType]="'timer'" disabled #dt3></owl-date-time>`

**This is my FormGroup settings**

`pickup_time: [{ value: '', disabled: true }],`

**This is the results**

![input](https://user-images.githubusercontent.com/17473507/98162950-bef77100-1eea-11eb-9b2f-ea6ee6cec58b.png)

I want the user to pickup time, but not allowed to manually update the `<input />`

**Comment by f3l1xss** [comment]
@Applicafroguy Did you manage to resolve this? I am currently facing the same problem

**Comment by f3l1xss** [comment]
Since it appears that the disabled attribute does not work, I 'fake' disabled the timer input using css:

https://stackoverflow.com/questions/5963099/how-do-i-disable-form-fields-using-css
.owl-dt-timer-content {
  pointer-events: none;
}
