### ISSUE TITLE
Angular 11 failed update

### ISSUE THREAD

**Issue by burner** [danielmoncada/date-time-picker#92]
I tried updating to angular 11 and it failed with

```
Package "@danielmoncada/angular-datetime-picker" has an incompatible peer dependency to "@angular/cdk" (requires "^8.0.0 || ^9.0.0 || ^10.0.0", would install "11.0.0").
```

**Comment by danielmoncada** [comment]
@burner haven't added ng11 support yet. I'll work on it this week.

**Comment by Barzille** [comment]
Any update on this?

**Comment by krisurnok** [comment]
Please let us know when we will get an update for Angular 11 version.

**Comment by jcompagner** [comment]
all our tst that we do (we are already on 11 for a while now) the component works fine
so the for me the peer depedencies can just be adjusted to also support 11

**Comment by danielmoncada** [comment]
so sorry, been super busy with everything at work. i'm allocating time this weekend to do this.

**Comment by jcompagner** [comment]
the new release didn't update these 3 peers yet i see:

https://github.com/danielmoncada/date-time-picker/blob/master/projects/picker/package.json#L27

**Comment by danielmoncada** [comment]
@jcompagner right. I'll make a separate PR for that

**Comment by danielmoncada** [comment]
merged with https://github.com/danielmoncada/date-time-picker/pull/106

@burner 
@Barzille 
@krisurnok 
@jcompagner 

newest version that supports ng11: https://www.npmjs.com/package/@danielmoncada/angular-datetime-picker

**Comment by burner** [comment]
@danielmoncada thank you so much. All other datetime picker I tried for angular/material are a big pile of :hankey: in comparison
