### ISSUE TITLE
UnixTimestampAdapter does not exist in published release

### ISSUE THREAD

**Issue by sedran** [danielmoncada/date-time-picker#97]
The following folder does not exist in the published release on npmjs:

https://github.com/danielmoncada/date-time-picker/tree/master/projects/picker/src/lib/date-time/adapter/unix-timestamp-adapter

Did I forgot something while developing the adapter? I think there are some files that should reference this adapter in order for npm build to put those files into the distribution.

**Comment by danielmoncada** [comment]
@sedran  yeah you forgot a few things. I'll create a PR today. Thanks

**Comment by sedran** [comment]
Hello @danielmoncada, any update on this issue? In case you are busy, if you tell me which files need to be changed I can try to help.

**Comment by danielmoncada** [comment]
fixed in https://github.com/danielmoncada/date-time-picker/pull/104

**Comment by danielmoncada** [comment]
@sedran should be fixed in 10.2.0. thanks!
