### ISSUE TITLE
timezone problem

### ISSUE THREAD

**Issue by amarkes** [danielmoncada/date-time-picker#99]
I have a timezone problem, when I change the minutes they change the time alone, does anyone know how to proceed with this?

![ezgif com-gif-maker](https://user-images.githubusercontent.com/6019683/102498170-62928000-4058-11eb-9ae0-d5ae84952066.gif)

**Comment by danielmoncada** [comment]
@amarkes  are you still having a problem?

**Comment by danielmoncada** [comment]
stale, no response from OP
